development:
  adapter: postgresql
  encoding: unicode
  database: mentu
  host: localhost
  username: mentu
  password: secret
test:
  adapter: postgresql
  encoding: unicode
  database: mentu_test
  host: localhost
  pool: 5
  username: mentu
  password: secret
production:
  adapter: postgresql
  encoding: unicode
  database: mentu_production
  pool: 25
  username: root
  password: password